In [44]:
#exercise 1
import numpy as np
arr=np.arange(10, 34, 1)
arr.reshape(8,3)
arr1=np.array_split(arr,4)
arr1

[array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27]),
 array([28, 29, 30, 31, 32, 33])]

In [59]:
#exercise 2
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
sort_row=sampleArray[:,sampleArray[1,:].argsort()]
sort_column=sampleArray[:,sampleArray[:,1].argsort()]
print('Sort array by the second row\n ',sort_row)
print('Sort array by the second column\n',sort_column)

Sort array by the second row
  [[73 43 34]
 [12 22 82]
 [66 94 53]]
Sort array by the second column
 [[43 34 73]
 [22 82 12]
 [94 53 66]]


In [54]:
#exercise 3
sampleArray1 = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(np.amax(sampleArray1,0))
print(np.amin(sampleArray1,1))

[82 94 73]
[34 12 53]


In [57]:
#exercise 4
sampleArray2 = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray2=np.delete(sampleArray2,1,axis=1)
sampleArray2=np.insert(sampleArray2,1,newColumn,axis=1)
sampleArray2

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])