In [14]:
import numpy as np

In [44]:
np.__version__

'1.21.5'

In [46]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [47]:
arr=np.array(42)
print(arr)

42


In [51]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])

10


In [50]:
arr.ndim

2

In [60]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray[0:3,2])

[33 66 99]


In [66]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='u2')

print(arr)
print(arr.dtype)

[1 2 3 4]
uint16


In [68]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series

print(myvar)

day1    420
day2    380
day3    390
dtype: int64
