In [69]:
#exercise 1
import numpy as np
arr=np.arange(2, 18, 2)
arr=arr.reshape(4,2)
arr.astype('u2')
print('The shape of an array:',arr.shape)
print('Array dimensions :',arr.ndim)
print('The Length of each element of the array in bytes: ',len(arr[:]))

The shape of an array: (4, 2)
Array dimensions : 2
The Length of each element of the array in bytes:  4


In [72]:
#exercise 2
arr1=np.arange(100,200,10)
arr1=arr1.reshape(5,2)
arr1

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [73]:
#exercise 3
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[:,2]

array([33, 66, 99])

In [76]:
#exercise 4
sampleArray1= np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray1[0:5:2,1:5:2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [81]:
#exercise 5
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arrResult=arrayOne+arrayTwo
print('the addition of two arrays: \n',arrResult)
print('the square root of all elements: \n',arrResult**2)


the addition of two arrays: 
 [[20 39 33]
 [25 25 28]]
the square root of all elements: 
 [[ 400 1521 1089]
 [ 625  625  784]]
